import './Home.scss';
import { Slideshow } from '../slideshow/Slideshow';
import { RegisterTree } from '../register-tree/RegisterTree';

export const Home = () => {
  return (
    <main>
      <RegisterTree />
      {/* Just filler text to demo scrolling. Header links scroll tp specific id tags */}
      <h1 id='About' className='anchor'>About</h1>
      <Slideshow/>
      <h1 id='Map' className='anchor'>Map</h1>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Ut etiam sit amet nisl purus. Tortor consequat id porta nibh venenatis cras sed. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Aliquet nibh praesent tristique magna. Ut pharetra sit amet aliquam id diam maecenas ultricies mi. Eu augue ut lectus arcu bibendum at varius. A erat nam at lectus urna duis convallis convallis tellus. Euismod lacinia at quis risus. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Orci phasellus egestas tellus rutrum tellus. Amet consectetur adipiscing elit ut aliquam purus.</p>
      <p>Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Etiam non quam lacus suspendisse faucibus. Tortor id aliquet lectus proin nibh. Odio eu feugiat pretium nibh ipsum consequat. A condimentum vitae sapien pellentesque habitant morbi. Massa sapien faucibus et molestie. Tempus iaculis urna id volutpat lacus laoreet non. Volutpat maecenas volutpat blandit aliquam etiam. In dictum non consectetur a erat nam at lectus urna. Vel pretium lectus quam id leo in vitae turpis massa. Morbi tristique senectus et netus et malesuada. Cras semper auctor neque vitae tempus quam pellentesque nec. Tortor at risus viverra adipiscing at in tellus integer feugiat. Accumsan in nisl nisi scelerisque eu ultrices.</p>
      <p>Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Sociis natoque penatibus et magnis dis parturient. Volutpat blandit aliquam etiam erat velit scelerisque. Viverra ipsum nunc aliquet bibendum enim facilisis. Gravida in fermentum et sollicitudin ac orci. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Risus at ultrices mi tempus. In est ante in nibh mauris cursus mattis molestie a. Diam maecenas sed enim ut. Sodales ut eu sem integer vitae justo eget. Et netus et malesuada fames ac turpis. Facilisis volutpat est velit egestas dui id ornare arcu odio. Ut enim blandit volutpat maecenas. Ut tellus elementum sagittis vitae et leo duis ut diam. Eros in cursus turpis massa tincidunt dui. Nascetur ridiculus mus mauris vitae ultricies. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Cursus metus aliquam eleifend mi in nulla posuere. Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Aliquet bibendum enim facilisis gravida neque.</p>
      <p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Sed tempus urna et pharetra pharetra massa massa ultricies mi. Ut etiam sit amet nisl purus. Tortor consequat id porta nibh venenatis cras sed. Morbi blandit cursus risus at ultrices mi tempus imperdiet nulla. Iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Aliquet nibh praesent tristique magna. Ut pharetra sit amet aliquam id diam maecenas ultricies mi. Eu augue ut lectus arcu bibendum at varius. A erat nam at lectus urna duis convallis convallis tellus. Euismod lacinia at quis risus. Amet volutpat consequat mauris nunc congue nisi vitae suscipit. Orci phasellus egestas tellus rutrum tellus. Amet consectetur adipiscing elit ut aliquam purus.</p>
      <p>Laoreet non curabitur gravida arcu ac tortor dignissim convallis aenean. Proin nibh nisl condimentum id venenatis a condimentum vitae sapien. Etiam non quam lacus suspendisse faucibus. Tortor id aliquet lectus proin nibh. Odio eu feugiat pretium nibh ipsum consequat. A condimentum vitae sapien pellentesque habitant morbi. Massa sapien faucibus et molestie. Tempus iaculis urna id volutpat lacus laoreet non. Volutpat maecenas volutpat blandit aliquam etiam. In dictum non consectetur a erat nam at lectus urna. Vel pretium lectus quam id leo in vitae turpis massa. Morbi tristique senectus et netus et malesuada. Cras semper auctor neque vitae tempus quam pellentesque nec. Tortor at risus viverra adipiscing at in tellus integer feugiat. Accumsan in nisl nisi scelerisque eu ultrices.</p>
      <p>Velit aliquet sagittis id consectetur purus ut faucibus pulvinar elementum. Sociis natoque penatibus et magnis dis parturient. Volutpat blandit aliquam etiam erat velit scelerisque. Viverra ipsum nunc aliquet bibendum enim facilisis. Gravida in fermentum et sollicitudin ac orci. Ullamcorper eget nulla facilisi etiam dignissim diam quis enim. Risus at ultrices mi tempus. In est ante in nibh mauris cursus mattis molestie a. Diam maecenas sed enim ut. Sodales ut eu sem integer vitae justo eget. Et netus et malesuada fames ac turpis. Facilisis volutpat est velit egestas dui id ornare arcu odio. Ut enim blandit volutpat maecenas. Ut tellus elementum sagittis vitae et leo duis ut diam. Eros in cursus turpis massa tincidunt dui. Nascetur ridiculus mus mauris vitae ultricies. Imperdiet nulla malesuada pellentesque elit eget gravida cum. Cursus metus aliquam eleifend mi in nulla posuere. Ultrices in iaculis nunc sed augue lacus viverra vitae congue. Aliquet bibendum enim facilisis gravida neque.</p>
      <br/>
    </main>
  );
}